PC_Room_Management/src/GUI/Login_QR.java
PC_Room_Management/src/GUI/Loginpage.java
PC_Room_Management/src/GUI/MainLogin.java
PC_Room_Management/src/GUI/SearchIDPW.java
PC_Room_Management/src/GUI/SeatFood_select.java

로그인 선택 페이지

---

PC_Room_Management/src/GUI/Login_QR.java
PC_Room_Management/src/GUI/RoundedButton.java
PC_Room_Management/src/GUI/Signin_frame.java

회원 가입 페이지에 카드번호, 이메일 추가

---

PC_Room_Management/src/GUI/User_Management.java

회원 관리 화면입니다

---

PC_Room_Management/src/GUI/User_Management.java

삭제, 뒤로가기 버튼 추가

---

PC_Room_Management/src/GUI/Sales_Management.java

음식 선택 화면 추가

---

PC_Room_Management/src/GUI/manager_login.java

관리자 로그인 화면 추가

---

PC_Room_Management/src/Chat/InquiryPage.java
PC_Room_Management/src/Main/MainLogin.java
PC_Room_Management/src/Manager/Manager_menu.java
PC_Room_Management/src/Manager/Sales_Management.java
PC_Room_Management/src/Manager/User_Management.java
PC_Room_Management/src/Manager/inquiry_management.java
PC_Room_Management/src/Manager/manager_login.java
PC_Room_Management/src/Select/Menu_select.java
PC_Room_Management/src/Select/Payment_page.java
PC_Room_Management/src/Select/SeatFood_select.java
PC_Room_Management/src/Select/Seat_select.java
PC_Room_Management/src/User/Login_QR_ID.java
PC_Room_Management/src/User/Loginpage.java
PC_Room_Management/src/User/QR_Login.java
PC_Room_Management/src/User/SearchIDPW.java
PC_Room_Management/src/User/Signin_frame.java

이벤트 처리 전체 코드 확인

---

PC_Room_Management/src/User/Loginpage.java

로그인페이지 흰색으로 변경

---

PC_Room_Management/src/User/SearchIDPW.java

아이디/비밀번호 찾기 레이블을 비밀번호 찾기 레이블로 변경하였습니다.

비밀번호 찾기 페이지 DB 연결했습니다.

---

PC_Room_Management/src/User/Signin_frame.java

회원 가입 페이지 수정

---

PC_Room_Management/src/User/Signin_frame.java

회원 가입 페이지 종료 없앰

---

PC_Room_Management/src/DB/Database.java
PC_Room_Management/src/Manager/User_Management.java
PC_Room_Management/src/Select/Payment_page.java

좌석 결제 페이지 추가

---

PC_Room_Management/src/User/Signin_frame.java

회원 가입 예외 처리 수정

---

PC_Room_Management/src/Select/Payment_page.java

회원 금액 메세지 추가

---

PC_Room_Management/src/DB/Database.java
PC_Room_Management/src/Select/Payment_page.java

좌석 결제 디비 수정

---

PC_Room_Management/src/DB/Database.java
PC_Room_Management/src/Manager/Manager_menu.java
PC_Room_Management/src/Select/Seat_select.java

DB 클래스 로그인 시 아이디 넘기기 수정

---

PC_Room_Management/src/DB/Database.java
PC_Room_Management/src/Main/MainLogin.java
PC_Room_Management/src/Manager/Manager_menu.java
PC_Room_Management/src/Manager/Sales_Management.java
PC_Room_Management/src/Manager/User_Management.java
PC_Room_Management/src/Select/Menu_select.java
PC_Room_Management/src/Select/Payment_page.java
PC_Room_Management/src/Select/Seat_select.java
PC_Room_Management/src/User/Login_QR_ID.java
PC_Room_Management/src/User/Loginpage.java
PC_Room_Management/src/User/QR_Login.java
PC_Room_Management/src/User/SearchIDPW.java
PC_Room_Management/src/User/Signin_frame.java

코드 통합 및 디비 클로즈

---

PC_Room_Management/src/DB/Database.java
PC_Room_Management/src/User/Signin_frame.java

회원가입 나이 삭제

---

PC_Room_Management/src/User/Signin_frame.java

회원가입 조건 수정

---

PC_Room_Management/src/Manager/Manager_menu.java
PC_Room_Management/src/Select/SeatFood_select.java
PC_Room_Management/src/Select/Seat_select.java

좌석 선택 로그인 시 대여중인 좌석에 로그인 되어 있는 아이디 넘어가지 않게 수정
좌석,음식 선택 창 홈 버튼 눌렀을 때 로그아웃 되게 수정

매니저 메뉴 빈 좌석 삭제 안되게 수정
